export const data1 = [
  {
    id: 1,
    content:
      "LMiTS (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by LMiTS.",
  },
  {
    id: 2,
    content:
      "This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application, LMiTS. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.",
  },
];

export const data2 = [
  {
    id: 1,
    content: `Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.`,
  },
  {
    id: 2,
    content: `Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to LMiTS Solutions Private Limited, R-22, 3rd Cross, Nash Square, 1st Floor, Electronic city phase-1, Bengaluru, Karnataka 560100 that is responsible for your information under this Privacy Policy.`,
  },
  {
    id: 3,
    content: `Country: where LMiTS or the owners/founders of LMiTS are based, in this case is IN`,
  },
  {
    id: 4,
    content: `Customer: refers to the company, organization or person that signs up to use the LMiTS Service to manage the relationships with your consumers or service users.`,
  },
  {
    id: 5,
    content: `Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit LMiTS and use the services.`,
  },
  {
    id: 6,
    content: `IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.`,
  },
  {
    id: 7,
    content: `Personnel: refers to those individuals who are employed by LMiTS or are under contract to perform a service on behalf of one of the parties.`,
  },
  {
    id: 8,
    content: `Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.`,
  },
  {
    id: 9,
    content: `Service: refers to the service provided by LMiTS as described in the relative terms (if available) and on this platform.`,
  },
  {
    id: 10,
    content: `Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.`,
  },
  {
    id: 11,
    content: `Website: LMiTS's site, which can be accessed via this URL: www.lmits.in`,
  },
  {
    id: 12,
    content: `You: a person or entity that is registered with LMiTS to use the Services.`,
  },
];

export const data3 = [
  {
    id: 1,
    content: `Name / Username`,
  },
  {
    id: 2,
    content: `Phone Numbers`,
  },
  {
    id: 3,
    content: `Country: where LMiTS or the owners/founders of LMiTS are based, in this case is IN`,
  },
  {
    id: 4,
    content: `Email Addresses`,
  },
  {
    id: 5,
    content: `Mailing Addresses`,
  },
  {
    id: 6,
    content: `Billing Addresses`,
  },
  {
    id: 7,
    content: `Debit/credit card numbers`,
  },
  {
    id: 8,
    content: `Password`,
  },
];

export const whatInfoExtra = [
  {
    id: 1,
    content: `Location (GPS): Location data helps to create an accurate representation of your interests, and this can be used to bring more targeted and relevant ads to potential customers.`,
  },
  {
    id: 2,
    content: `Phonebook (Contacts list): Your contacts list allows the website/app to be much more easy to use by the user, since accessing your contacts from the app makes you save tons of time.`,
  },
  {
    id: 3,
    content: `Camera (Pictures): Granting camera permission allows the user to upload any picture straight from the website/app, you can safely deny camera permissions for this website/app.
            `,
  },
  {
    id: 4,
    content: `Photo Gallery (Pictures): Granting photo gallery access allows the user to upload any picture from their photo gallery, you can safely deny photo gallery access for this website/app.`,
  },
];

export const howDoWeUseInfo = [
  {
    id: 1,
    content:
      "To personalize your experience (your information helps us to better respond to your individual needs)",
  },
  {
    id: 2,
    content:
      "To improve our website/app (we continually strive to improve our website/app offerings based on the information and feedback we receive from you)",
  },
  {
    id: 3,
    content:
      "To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)",
  },
  {
    id: 4,
    content: "To process transactions",
  },
  {
    id: 5,
    content: "To administer a contest, promotion, survey or other site feature",
  },
  {
    id: 6,
    content: "To send periodic emails",
  },
];

export const doWeShareInfo = [
  {
    id: 1,
    content:
      "We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal information to our successors-in-interest.",
  },
  {
    id: 2,
    content:
      "We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and the website/app, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through the website/app. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.",
  },
  {
    id: 3,
    content: `We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the website/app in a shared location, and type of the device used to visit the website/app. They may aggregate information about our advertising and what you see on the website/app and then provide auditing, research and reporting for us and our advertisers. We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and regulations.`,
  },
];

export const canIUpdateCreate = [
  {
    id: 1,
    content:
      "The rights you have to request updates or corrections to the information LMiTS collects depend on your relationship with LMiTS. Personnel may update or correct their information as detailed in our internal company employment policies.",
  },
  {
    id: 2,
    content: `Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account information at all times.`,
  },
  {
    id: 3,
    content: `You should be aware that it is not technologically possible to remove each and every record of the information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable.`,
  },
  {
    id: 4,
    content:
      "If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.",
  },
];

export const governingLaw = [
  {
    id: 1,
    content:
      "This Privacy Policy is governed by the laws of IN without regard to its conflict of laws provision. You consent to the exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US framework.",
  },
  {
    id: 2,
    content: `The laws of IN, excluding its conflicts of law rules, shall govern this Agreement and your use of the website/app. Your use of the website/app may also be subject to other local, state, national, or international laws.`,
  },
  {
    id: 3,
    content: `By using LMiTS or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or disclosure of your personal information will mean that you accept those changes.`,
  },
];

export const advertising = [
  {
    id: 1,
    content:
      "This website/app may contain third party advertisements and links to third party sites. LMiTS does not make any representation as to the accuracy or suitability of any of the information contained in those advertisements or sites and does not accept any responsibility or liability for the conduct or content of those advertisements and sites and the offerings made by the third parties.",
  },
  {
    id: 2,
    content: `Advertising keeps LMiTS and many of the websites and services you use free of charge. We work hard to make sure that ads are safe, unobtrusive, and as relevant as possible.`,
  },
  {
    id: 3,
    content: `Third party advertisements and links to other sites where goods or services are advertised are not endorsements or recommendations by LMiTS of the third party sites, goods or services. LMiTS takes no responsibility for the content of any of the ads, promises made, or the quality/reliability of the products or services offered in all advertisements.`,
  },
];

export const thirdPartyServices = [
  {
    id: 1,
    content: `We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services").`,
  },
  {
    id: 2,
    content: `You acknowledge and agree that LMiTS shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. LMiTS does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.`,
  },
  {
    id: 3,
    content: `Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.`,
  },
];

export const trackingTechnologies = [
  {
    heading: {
      title: "Google Map API",
      content: [
        {
          description:
            "Google Maps API is a robust tool that can be used to create a custom map, a searchable map, check-in functions, display live data synching with location, plan routes, or create a mashup just to name a few.",
        },
        {
          description:
            "Google Maps API may collect information from You and from Your Device for security purposes.",
        },
        {
          description:
            "Google Maps API collects information that is held in accordance with its Privacy Policy.",
        },
      ],
    },
  },
  {
    heading: {
      title: "Cookies",
      content: [
        {
          description:
            "We use Cookies to enhance the performance and functionality of our $platform but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the $platform as we would not be able to remember that you had logged in previously.",
        },
      ],
    },
  },
  {
    heading: {
      title: "Local Storage",
      content: [
        {
          description:
            "Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header.",
        },
      ],
    },
  },
  {
    heading: {
      title: "Sessions",
      content: [
        {
          description: `$elnombre uses "Sessions" to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser.`,
        },
      ],
    },
  },
];

export const personalData = [
  {
    id: 1,
    content:
      "Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect.",
  },
  {
    id: 2,
    content: `Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it.`,
  },
  {
    id: 3,
    content: `Personal data should be held no longer than necessary to fulfil its purpose.`,
  },
  {
    id: 4,
    content: `People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization.`,
  },
];
