export const definitionsAndkeyterm = [
  {
    title: "Definitions and key terms",
    description:
      "To help explain things as clearly as possible in this Return & Refund Policy, every time any of these terms are referenced, are strictly defined as:",
    content: [
      {
        text:
          "Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your",
      },
      {
        text:
          "Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to LMiTS, that is responsible for your information under this Return & Refund Policy.",
      },
      {
        text:
          "Customer: refers to the company, organization or person that signs up to use the LMiTS Service to manage the relationships with your consumers or service users.",
      },
      {
        text:
          "Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit LMiTS and use the services.",
      },
      {
        text:
          "Service: refers to the service provided by LMiTS as described in the relative terms (if available) and on this platform.",
      },
      {
        text: "Website: site, which can be accessed via this URL: www.lmits.in",
      },
      {
        text:
          "You: a person or entity that is registered with LMiTS to use the Services.",
      },
    ],
  },
];

export const returnAndRefund = [
  {
    title: "Return & Refund Policy",
    content: [
      {
        text:
          "Thanks for shopping at LMiTS. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you’re exploring, evaluating, and purchasing our products.",
      },
      {
        text:
          "As with any shopping experience, there are terms and conditions that apply to transactions at LMiTS. We’ll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at LMiTS, you agree to the terms set forth below along with Policy.",
      },
      {
        text:
          "If there’s something wrong with the you bought, or if you are not happy with it, you have 2 weeks to issue a refund and return your .",
      },
      {
        text:
          "If you would like to return a product, the only way would be if you follow the next guidelines:",
      },
    ],
  },
];

export const refunds = [
  {
    title: "Refunds",
    content: [
      {
        text:
          "We at  ourselves to serving our customers with the best products. Every single product that you choose is thoroughly inspected, checked for defects and packaged with utmost care. We do this to ensure that you fall in love with our products.",
      },
      {
        text:
          "Sadly, there are times when we may not have the product(s) that you choose in stock, or may face some issues with our inventory and quality check. In such cases, we may have to cancel your order. You will be intimated about it in advance so that you don't have to worry unnecessarily about your order. If you have purchased via Online payment (not Cash on Delivery), then you will be refunded once our team confirms your request.",
      },
      {
        text:
          "We carry out thorough quality check before processing the ordered item. We take utmost care while packing the product. At the same time we ensure that the packing is good such that the items won’t get damaged during transit. Please note that LMiTS is not liable for damages that are caused to the items during transit or transportation.",
      },
      {
        text:
          "We will revise your returned product as soon as we receive it and if it follows the guidelines addressed above, we will proceed to issue a refund of your purchase. Your refund may take a couple of days to process but you will be notified when you receive your money.",
      },
    ],
  },
];

export const shipping = [
  {
    title: "Shipping",
    content: [
      {
        text:
          "LMiTS is not responsible for return shipping costs. Every shipping has to be paid by the customer, even if the item had free shipping in the first place, the customer has to pay for the shipping in return.",
      },
    ],
  },
];

export const yourConsent = [
  {
    title: "Your Consent",
    content: [
      {
        text:
          "By using our website/app, registering an account, or making a purchase, you hereby consent to our Return & Refund Policy and agree to its terms.",
      },
    ],
  },
];

export const changesToOurReturn = [
  {
    title: "Changes To Our Return & Refund Policy",
    content: [
      {
        text:
          "Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Return & Refund Policy. If you do not want to agree to this or any updated Return & Refund Policy, you can delete your account.",
      },
    ],
  },
];

export const contactUs = [
  {
    ttitle: "Contact Us",
    content: [
      {
        text: `Via Email: support@lmits.in`,
      },
      {
        text: `Via Phone Number: +91 86200 87300`,
      },
    ],
  },
];
